import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Nav from "./Nav";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <body className={inter.className + " h-full flex"}>
      <div className="w-60 border-r shrink-0 border-b sticky top-0 z-50  mb-10 h-full">
        <Nav />
      </div>
      <div className="flex-1 w-full px-4 sm:px-0 mx-auto">{children}</div>
    </body>
  );
}
